language: python

dist: xenial

cache: pip

python:
  - 3.6
  - 3.7

install:
  - "pip install --upgrade pip"
  - "pip install ."
  - "pip install --upgrade .[test]"

matrix:
  include:
    - os: windows
      language: sh
      python: "3.6"
      before_install:
        - choco install python --version 3.6
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"

script:
  - pytest tests --cov=bentoml

after_success:
  - codecov
